adobe/aem-project-archetype

src/main/archetype/core/pom.xml, src/main/archetype/pom.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/content/servicecomponent/HelloServiceProxy.java, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/content/servicecomponent/servicecomponent.html, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/content/topnav/Topnav.java, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/page/page/CopyrightHelper.java
Moving logic to activate() method to avoid multiple executions of the same code.
=> Sightly java coding

src/main/archetype/core/pom.xml, src/main/archetype/pom.xml
Adding dependencies for sling-model support
=> [FV] adding support for Sling-models (@Inject support)

README.md, src/main/resources/META-INF/maven/archetype-metadata.xml
README.MD build instructions #22
semantic versioning support #23
=> README.MD build instructions, semantic versioning support

src/main/archetype/pom.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/clientlib-base/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/content/carousel/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/content/carousel/_cq_editConfig.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/content/tabs/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/content/tabs/_cq_editConfig.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/content/tabs/_cq_template/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/content/teaser/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/content/__contentFolderName__/en/.content.xml
- updated dependency of core-components to version 2.2.0
- added proxy component for teaser, tabs and carousel core-component
- added example content for teaser, tabs and carousel
=> Update core-component version (fixes #128)

README.md, src/main/archetype/pom.xml, src/main/archetype/ui.apps/pom.xml, src/main/resources/META-INF/maven/archetype-metadata.xml, src/test/resources/projects/basic/archetype.properties
- add core.wcm.components.examples as subpackage of ui.apps content package
- update dependency of core components version
fixes #148
=> Integration of Component Library examples content package

src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/content/image/_cq_editConfig.xml
=> add allowedMimetype for crop config of image component

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CODE_OF_CONDUCT.md, COPYRIGHT
=> Add code of conduct, copyright and contributing files

.circleci/config.yml, src/main/archetype/core/pom.xml, src/main/archetype/pom.xml
- add javax.annotation dependency
this fixes #170
=> Support JDK11 in generated maven project

src/main/archetype/core/pom.xml, src/main/archetype/core/src/test/java/core/filters/LoggingFilterTest.java, src/main/archetype/core/src/test/java/core/listeners/SimpleResourceListenerTest.java, src/main/archetype/core/src/test/java/core/models/HelloWorldModelTest.java, src/main/archetype/core/src/test/java/core/schedulers/SimpleScheduledTaskTest.java, src/main/archetype/core/src/test/java/core/servlets/SimpleServletTest.java, src/main/archetype/it.launcher/pom.xml, src/main/archetype/it.tests/pom.xml, src/main/archetype/pom.xml
* Updated archetype to use Junit 5
=> Move to JUnit5 #165

README.md, src/main/archetype/pom.xml, src/main/resources/META-INF/maven/archetype-metadata.xml, src/test/resources/projects/basic/archetype.properties
* Added new 6.5 uberjar (now default)
* Updated uberjar versions
Fixes #176
=> Update Uberjar version(s)

src/main/archetype/pom.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/content/contentfragment/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/content/contentfragment/_cq_editConfig.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/content/contentfragmentlist/.content.xml
* Update core components version
* Added proxy for contentfragment and contentfragmentlist component
(Fixes #181)
=> Update core-components dependency to 2.4.0 #181

README.md
Updating location of WKND Tutorial in README.md
=> Updated location of WKND Tutorial

README.md, src/main/archetype/pom.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/clientlib-dependencies/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/content/accordion/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/content/accordion/_cq_editConfig.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/content/accordion/_cq_template/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/content/button/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/content/container/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/content/download/.content.xml
- updates Core Components dependency to 2.5.0
- adds proxies for accordion, button, container and download
- adds missing components to main README.md
=> Update project archetype for Core Components 2.5.0

src/main/archetype/pom.xml
=> Removal of maven-eclipse-plugin and maven-idea-plugin from POM

src/main/archetype/core/pom.xml, src/main/archetype/core/src/main/java/core/filters/package-info.java, src/main/archetype/core/src/main/java/core/listeners/package-info.java, src/main/archetype/core/src/main/java/core/models/package-info.java, src/main/archetype/core/src/main/java/core/schedulers/package-info.java, src/main/archetype/core/src/main/java/core/servlets/package-info.java, src/main/archetype/it.launcher/pom.xml, src/main/archetype/it.tests/pom.xml, src/main/archetype/it.tests/src/main/java/it/tests/package-info.java, src/main/archetype/pom.xml
=> Use bnd-maven-plugin instead of maven-bundle-plugin

src/main/archetype/README.md
Document the option needed to get ui.frontend folder so that others don't end up with issue #224
Update documentation
#224 
No clear how to get the ui.frontend folder if you miss the option.
Documentation
- [ x ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ x ] My code follows the code style of this project.
- [ x ] My change requires a change to the documentation.
- [ x ] I have updated the documentation accordingly.
- [ x ] I have read the **CONTRIBUTING** document.
- [ x ] I have added tests to cover my changes.
- [ x ] All new and existing tests passed.
=> Add ui.frontend info to README

src/main/archetype/pom.xml
There is a duplicate entry for biz.aQute.bnd
Remove duplicate entry.
https://github.com/adobe/aem-project-archetype/issues/223
ran mvn in issue
- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x ] My code follows the code style of this project.
- [x ] I have read the **CONTRIBUTING** document.
=> remove duplicate entry

README.md, src/main/archetype/pom.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/content/experiencefragment/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/content/experiencefragment/_cq_editConfig.xml, src/main/archetype/ui.frontend/src/main/webpack/components/content/experiencefragment/scss/experiencefragment.scss
- updates Core Components dependency to 2.6.0
- adds proxy for the experience fragment component
- adds missing components to main README.md
=> Update project archetype for Core Components 2.6.0

src/main/archetype/ui.frontend/tsconfig.json, src/main/archetype/ui.frontend/webpack.common.js
Simplifies linting rules and avoids unnecessary processing.
issue #231 
Tested against the generated project to ensure that files within the src directory continue to get linted...
=> Fix for Issue #231

src/main/archetype/pom.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/content/embed/.content.xml
- bumps Core Components dependency to 2.7.0
- adds proxy Embed component
=> Update Core Components dependency to 2.7.0

src/main/archetype/core/src/main/java/core/models/HelloWorldModel.java
Added additional null check
To improve generated code quality and avoid a warning on potential NPE
Generated a new project from the archetype and checked that it works.
=> possible npe fix

src/main/archetype/dispatcher.ams/src/conf.d/rewrites/__contentFolderName___rewrite.rules, src/main/archetype/dispatcher.cloud/src/conf.d/rewrites/rewrite.rules
dynamic replace us/en with user input
fixes #258
=> Should not assume language in Rewrite Rules

src/main/resources/META-INF/maven/archetype-metadata.xml
=> Add default to language_country to en_us

src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/content/image/_cq_editConfig.xml
- accepts expects a regex, escape the +
=> [Image] Drag & drop SVG on image component not working

src/main/archetype/pom.xml
https://github.com/adobe/aem-project-archetype/issues/276
=> feat: Update htl-maven-plugin: 1.0.6 -> 1.3.0-1.4.0

src/main/archetype/pom.xml
Updates Core Components dependency to 2.8.0
=> Update Core Components dependency to 2.8.0

src/main/archetype/ui.frontend/.gitignore
ignores css,js and other artifacts compiled and moved into the dist folder
Small update to safely ignore compiled css, js and other artifacts from source control.
=> ignore distributed files

README.md
- remove duplicate content and add link to documentation page
fixes #291
=> Reduce Archetype Readme

src/main/archetype/ui.content/src/main/content/jcr_root/content/__contentFolderName__/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/content/dam/__contentFolderName__/.content.xml
=> Assign Cloud Configuration on root content page

README.md
=> Update compatibility with cloud

src/main/archetype/all/pom.xml, src/main/archetype/it.launcher/pom.xml, src/main/archetype/it.tests/pom.xml, src/main/archetype/ui.apps/pom.xml, src/main/archetype/ui.content/pom.xml
=> Set generated project dependencies with version property

src/main/archetype/dispatcher.ams/src/conf.d/rewrites/__contentFolderName___rewrite.rules, src/main/archetype/dispatcher.cloud/src/conf.d/rewrites/rewrite.rules, src/main/archetype/pom.xml, src/main/archetype/ui.content/src/main/content/jcr_root/conf/__confFolderName__/settings/wcm/templates/page-content/structure/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/content/__contentFolderName__/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/content/__contentFolderName__/language-masters/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/content/__contentFolderName__/language-masters/en/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/content/__contentFolderName__/us/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/content/__contentFolderName__/us/en/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/content/experience-fragments/__contentFolderName__/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/content/experience-fragments/__contentFolderName__/language-masters/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/content/experience-fragments/__contentFolderName__/language-masters/en/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/content/experience-fragments/__contentFolderName__/language-masters/en/site/header/master/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/content/experience-fragments/__contentFolderName__/us/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/content/experience-fragments/__contentFolderName__/us/en/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/content/experience-fragments/__contentFolderName__/us/en/site/header/master/.content.xml, src/main/archetype/ui.frontend.angular/README.md, src/main/archetype/ui.frontend.angular/src/environments/environment.ts, src/main/archetype/ui.frontend.angular/src/index.html, src/main/archetype/ui.frontend.react/.env.development, src/main/archetype/ui.frontend.react/README.md, src/main/archetype/ui.frontend.react/public/index.html
- iterate over array and set value based on index instead of getting the value via the array get method
fixes #271
=> Placeholders with String.split function are not getting replaced

src/main/archetype/dispatcher.ams/src/conf.d/rewrites/__contentFolderName___rewrite.rules, src/main/archetype/dispatcher.cloud/src/conf.d/rewrites/rewrite.rules
Account for other resource extensions that can be resolved from the Site content tree.
See: #337 
Validated using the WKND Tutorial locally on a AEM Author/Pub/Dispatcher
- [] I have added tests to cover my changes.
=> Fix Apache/Rewrite Rule Core Component issue

src/main/archetype/ui.frontend.react/package.json
After generating a new project using Archetype 23 and a parameter of `frontendModule="react"` the project builds and deploys as expected to a local AEM instance.
However, when running the webpack development server via `npm start` the following error is thrown:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
at validateString (internal/validators.js:118:11)
at Object.join (path.js:1039:7)
at noopServiceWorkerMiddleware (/Users/dgordon/Desktop/l758-fe-react/ui.frontend/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
at Layer.handle [as handle_request] (/Users/dgordon/Desktop/l758-fe-react/ui.frontend/node_modules/express/lib/router/layer.js:95:5)
at trim_prefix …
```
=> Bump react-scripts version to 3.4.0

src/main/archetype/archetype.properties, src/main/resources/META-INF/maven/archetype-metadata.xml
=> Capture properties used to create a project with the archetype

src/main/archetype/core/pom.xml
Minor convenience, added the `core.wcm.components.core` dependency to the `core` POM file. Most customers will eventually extend AEM core components and will need this dependency set.
=> Core Component Dependency

src/main/archetype/ui.frontend.general/src/main/webpack/components/_helloworld.js
Minor update to the ui.frontend/src/main/webpack/components/_helloworld.js
1. remove unused `that` var;
2. move `init` below the function where it is defined to address the build error
This fixes issue 392:
https://github.com/adobe/aem-project-archetype/issues/392
I was testing the ui.frontend build to determine if it works
=> use `init` after it is defined, remove unused `that` var

src/main/archetype/it.tests/src/main/java/it/tests/CreatePageIT.java, src/main/archetype/it.tests/src/main/java/it/tests/GetPageIT.java
Fix Cloud Manager code check violations for project generated with the AEM as a Cloud Service profile.
#404 
Generated reference projects should pass code scans.
=> Fix CM code check violations

src/main/archetype/ui.content/src/main/content/jcr_root/conf/__appId__/settings/cloudconfigs/commerce/.content.xml, src/main/resources/META-INF/archetype-post-generate.groovy
Adapt cloud services config for CIF to AEM as a Cloud Service which already comes with a default config and uses a different resource type then the on-prem version of the CIF connector.
Prepare CIF based projects for AEM as a Cloud Service
=> Adapt cloud services config for CIF to AEM as a Cloud

src/main/archetype/README-CIF.md, src/main/archetype/README.md, src/main/resources/META-INF/archetype-post-generate.groovy, src/main/resources/META-INF/maven/archetype-metadata.xml
Fix readme generation for CIF based project by moving the CIF part to its own readme.md file.
=> Fix CIF readme generation

src/main/archetype/pom.xml
Update the GraphQL client dependency to version `1.6.0`
#422 
Update to the latest version of  `graphql-client`
=> @releng Update the graphql-client dependency to version 1.6.0

src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/commerce/teaser/.content.xml
Fixes wrong placeholder for `imageDelegate` property.
-
=> CIF-1211 - fix wrong imageDelegate

src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/button/.content.xml
Button component should use correct super resource type for commerce projects. CIF core components provide an extended button component (based on the WCM core component button) which allows to link to products or categories direct.y
=> CIF-1525 use correct super resource type for button 

src/main/archetype/pom.xml
Update to the latest CIF dependencies.
=> @trivial - update to latest CIF dependencies

README.md, src/main/archetype/all/pom.xml, src/main/archetype/archetype.properties, src/main/archetype/pom.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/clientlibs/clientlib-base/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/conf/__appId__/_sling_configs/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/conf/__appId__/_sling_configs/_rep_policy.xml, src/main/archetype/ui.content/src/main/content/jcr_root/content/__appId__/.content.xml, src/main/resources/META-INF/maven/archetype-metadata.xml, src/test/resources/projects/basic/archetype.properties, src/test/resources/projects/cif-cloud/archetype.properties, src/test/resources/projects/cif/archetype.properties, src/test/resources/projects/cloud/archetype.properties, src/test/resources/projects/frontend-angular/archetype.properties, src/test/resources/projects/frontend-general/archetype.properties, src/test/resources/projects/frontend-react/archetype.properties
=> Added support for Adobe Client Data Layer

src/main/archetype/pom.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/clientlibs/clientlib-base/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/pdfviewer/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/progressbar/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/conf/__appId__/_sling_configs/.content.xml
=> Add support for PDF Viewer Component

README.md
=> Updated to new location of tutorial

src/main/archetype/ui.tests/test-module/wdio.conf.cloud.js
Improve UI test module execution (stability + performance) for cloud case (test executed in Docker)
Modified Selenium browsers capabilities for cloud execution
We experienced recently issues in AEMaaCS where UI test module would fail because of browser page crashing in Docker container.
1. Test module *not* including the fix got executed ~50 times : we got multiple failures due to browser page crash in Docker container
2. Test module including the fix got executed ~50 times : no cases of browser page crash
=> Improve test execution stability and performance in Docker (cloud case)

src/main/archetype/dispatcher.ams/src/conf.d/available_vhosts/aem_author.vhost, src/main/archetype/dispatcher.ams/src/conf.d/available_vhosts/aem_publish.vhost, src/main/archetype/dispatcher.ams/src/conf.d/mimetypes3d.conf, src/main/archetype/dispatcher.ams/src/conf.d/rewrites/base_rewrite.rules, src/main/archetype/dispatcher.ams/src/conf.d/variables/ams_default.vars, src/main/archetype/dispatcher.ams/src/conf.dispatcher.d/filters/ams_publish_filters.any
New config changes introduced in AMS 
Latest updated for the configurations that were introduced for the customers
This has been tested across multiple customer environments 
config changes + one new config file added
- [ x] Breaking change (fix or feature that would cause existing functionality to change)
- [ x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ x] My code follows the code style of this project.
- [x ] I have read the **CONTRIBUTING** document.
=> ams dispatcher configuration changes

src/main/archetype/ui.frontend.react/README.md, src/main/archetype/ui.frontend.react/package.json, src/main/archetype/ui.frontend.react/src/App.js, src/main/archetype/ui.frontend.react/src/components/Page/Page.js, src/main/archetype/ui.frontend.react/src/components/Page/Page.test.js, src/main/archetype/ui.frontend.react/src/components/RouteHelper/RouteHelper.test.js, src/main/archetype/ui.frontend.react/src/components/Text/Text.js, src/main/archetype/ui.frontend.react/src/components/Text/Text.test.js, src/main/archetype/ui.frontend.react/src/index.js
=> issue/466 renaming spa libraries to non-deprecated versions

src/main/archetype/pom.xml
fixes #437 
- locally building different combinations
- built-in archetype tests
- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] All new and existing tests passed.
=> Project creation fails for AEM type 'cloud' and 'no examples'

src/main/archetype/ui.frontend.angular/pom.xml, src/main/archetype/ui.frontend.general/pom.xml, src/main/archetype/ui.frontend.react/pom.xml
=> Make UI Frontend Module naming consistent with other modules

src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/page/customheaderlibs.html, src/main/archetype/ui.frontend.angular/proxy.conf.json, src/main/archetype/ui.frontend.angular/src/index.html
The browser doesn't reload after the local development server detected changes to the local code when developing an Angular Frontend. This is because the current proxy configuration inadvertently proxied `/content/**.html` from AEM.
Updates to `proxy.conf.json` to only proxy the `.model.json`, images and client libraries from AEM. Also includes an addition of `<base href>` which is needed for Angular to understand the context in which to load relative resources.
Fixes for Issue #362 
See issue #362 
1. Generating a new Angular project with the following properties:
```
groupId=archetype.it
artifactId=testing-frontend-angular
appId=testing-frontend-angular
package=it.pkg
version=0.1-SNAPSHOT
appTitle=Test Angular Frontend Project
aemVersion=6.5.0
sdkVersion=latest
languageCountry=en_us …
```
=> Issue 362 - Angular local dev server changes are not reflected

src/main/archetype/ui.frontend.general/src/main/webpack/static/index.html
=> Webpack static index does not use variables when referencing clientlib

src/main/archetype/ui.frontend.general/src/main/webpack/components/_contentfragment.scss, src/main/archetype/ui.frontend.general/src/main/webpack/components/_embed.scss, src/main/archetype/ui.frontend.general/src/main/webpack/components/_experiencefragment.scss, src/main/archetype/ui.frontend.general/src/main/webpack/components/_navigation.scss, src/main/archetype/ui.frontend.general/src/main/webpack/components/_pdfviewer.scss, src/main/archetype/ui.frontend.general/src/main/webpack/components/_progressbar.scss, src/main/archetype/ui.frontend.general/src/main/webpack/components/_separator.scss, src/main/archetype/ui.frontend.general/src/main/webpack/components/_teaser.scss
=> Add default styling for new components/elements in ui.frontent.general

src/main/archetype/ui.content/src/main/content/jcr_root/conf/__appId__/settings/wcm/template-types/xf/structure/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/conf/__appId__/settings/wcm/templates/xf-web-variation/structure/.content.xml
=> XF Template should use xfpage component

src/main/archetype/dispatcher.ams/src/conf.d/available_vhosts/__appId___publish.vhost, src/main/archetype/dispatcher.ams/src/conf.d/available_vhosts/aem_author.vhost, src/main/archetype/dispatcher.ams/src/conf.d/available_vhosts/aem_lc.vhost, src/main/archetype/dispatcher.ams/src/conf.d/available_vhosts/aem_publish.vhost, src/main/archetype/dispatcher.ams/src/conf.d/dispatcher_vhost.conf, src/main/archetype/dispatcher.ams/src/conf.dispatcher.d/available_farms/000_ams_author_farm.any, src/main/archetype/dispatcher.ams/src/conf.dispatcher.d/available_farms/001_ams_lc_farm.any, src/main/archetype/dispatcher.ams/src/conf.dispatcher.d/available_farms/999_ams_publish_farm.any
This fixes #441
All includes now refer to relative file paths instead of absolute ones
#441 
Eases reusing the same dispatcher configuration on different platforms (even on local development computers)
This is just following what has been done in `dispatcher.cloud` already and is currently in use in one customer project.
=> convert absolute file paths to relative ones

src/main/archetype/pom.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/commerce/addressbook/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/commerce/breadcrumb/.content.xml
* Update CIF Core Components version to last release 1.3.0
* add new proxy components for two new components introduced in CIF Core Components 1.3.0
n/a
=> Update CIF Core Components version

src/main/archetype/pom.xml
- update bnd version to 5.1.2
fixes #479
=> Update Bnd to 5.1.2

src/main/archetype/all/pom.xml
New ui.config package should be installed with the all package
=> Add ui.config package to all container package

src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/clientlibs/clientlib-grid/less/grid.less
- align breakpoints with UI Layout Editor
fixes #410
=> Breakpoints in grid.less do not match AEM UI Layout Editor

maven-win.yml
=> Add GH action for building on Windows

src/main/archetype/README.md
Updated the generated readme to include information about the generated project, including updated build commands
This is a fix for Issue #444
=> Updated Readme to reflect archetype updates

src/main/archetype/pom.xml
=> Fix erroneous and misleading message output by the maven-enforcer-plugin

README.md, VERSIONS.md
=> update VERSIONS.md and README.md for release 24

src/main/archetype/ui.content/src/main/content/jcr_root/conf/__appId__/settings/wcm/template-types/page/initial/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/conf/__appId__/settings/wcm/template-types/page/structure/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/conf/__appId__/settings/wcm/templates/page-content/initial/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/conf/__appId__/settings/wcm/templates/page-content/structure/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/conf/__appId__/settings/wcm/templates/xf-web-variation/structure/.content.xml
See https://github.com/adobe/aem-guides-wknd/issues/130
=> Updated containers to be responsive. 

src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/clientlibs/clientlib-cif/.content.xml
- replace no longer existing productlist clientlib with productcollection
Manually tested.
=> CIF-1640 - Productcollection clientlib is not included in Venia demo

src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/commerce/miniaccount/.content.xml
Minor fix to use the correct component name.
CIF-1611
=> Fix mini account component name

src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/clientlibs/clientlib-cif/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/commerce/categorycarousel/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/conf/__appId__/settings/wcm/policies/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/conf/__appId__/settings/wcm/templates/page-content/policies/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/conf/__appId__/settings/wcm/templates/xf-web-variation/policies/.content.xml
* added new carousel clientlib for CIF
CIF-1608
Manually.
=> CIF-1608 - Category Carousel Component

src/main/archetype/pom.xml
=> Update to Core Components 2.12.0

src/main/archetype/pom.xml
=> Update to Core Components 2.12.1

src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/commerce/teaser/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/conf/__appId__/settings/wcm/policies/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/conf/__appId__/settings/wcm/templates/page-content/policies/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/conf/__appId__/settings/wcm/templates/xf-web-variation/policies/.content.xml
* fixed title and description of commerce teaser proxy component
* added content policy for commerce teaser
CIF-1678
Updated commerce teaser to latest Core WCM Teaser.
Manually.
=> CIF-1678 - Commerce Teaser should align HTL files with WCM core component

src/main/archetype/pom.xml
Update the version of the aemanalyser-maven-plugin to 0.0.16
=> Update aemanalyser-maven-plugin version

src/main/archetype/pom.xml
=> Update core components to 2.13.0

src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/commerce/catalogpage/customfooterlibs.html, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/commerce/catalogpage/customheaderlibs.html
* added missing client libraries to catalogpage component
CIF-1765
Catalog page rendering is broken without these client librbabries.
Manually.
=> CIF-1765 - Update AEM archetype to fix the catalogpage as in CIF-1501

src/main/archetype/pom.xml
=> @trivial - update to CIF 1.6.0 dependencies

src/main/archetype/pom.xml
Updating spa.project.core 1.1.0 to 1.2.0
Updating project dependency to point to project aem-spa-project-core
=> Updating spa.project.core 1.1.0 to 1.2.0

src/main/archetype/ui.tests/Dockerfile
Fixing issue https://github.com/adobe/aem-project-archetype/issues/571
This PR fixes issue https://github.com/adobe/aem-project-archetype/issues/571
https://github.com/adobe/aem-project-archetype/issues/571
Fixing issue https://github.com/adobe/aem-project-archetype/issues/571
Tested Docker image build locally + in AEMaaCS pipeline
A fix for issue https://github.com/adobe/aem-project-archetype/issues/571
=> add missing dependencies to docker image build

src/main/archetype/ui.config/src/main/content/jcr_root/apps/__appId__/osgiconfig/config/org.apache.sling.commons.log.LogManager.factory.config-__appId__.config, src/main/archetype/ui.config/src/main/content/jcr_root/apps/__appId__/osgiconfig/config/org.apache.sling.commons.log.LogManager.factory.config~__appId__.cfg.json
=> #557 adjust logging settings

src/main/archetype/core/pom.xml, src/main/archetype/pom.xml, src/main/archetype/ui.apps/pom.xml
* Use new AEM CIF SDK API as dependency for all CIF cloud projects. This artifact indicates all dependencies which are included with the CIF add-on on AEMaaCS.
* Updated CIF Core components and GraphQL client versions to latest release. 
* Create a new Commerce project
```bash
mvn -B archetype:generate \
-D archetypeVersion=26-SNAPSHOT \
-D appTitle="My Site" \
-D appId="mysite" \
-D groupId="com.mysite" \
-D aemVersion="cloud" \
-D includeCommerce="y" \
-D commerceEndpoint="https://mymagento.com/graphl"
```
* Build and install project on latest AEM SDK + CIF add-on SDK.
* Check that the project installs properly and all dependencies are fulfilled.
=> CIF-1742 - Add AEM CIF SDK API as dependency for CIF cloud projects

src/main/archetype/dispatcher.ams/README.md, src/main/archetype/dispatcher.ams/immutable.files, src/main/archetype/dispatcher.ams/src/conf.d/allowlists/000_base_allowlist.rules, src/main/archetype/dispatcher.ams/src/conf.d/available_vhosts/__appId___publish.vhost, src/main/archetype/dispatcher.ams/src/conf.d/available_vhosts/aem_author.vhost, src/main/archetype/dispatcher.ams/src/conf.d/available_vhosts/aem_lc.vhost, src/main/archetype/dispatcher.ams/src/conf.d/available_vhosts/aem_publish.vhost, src/main/archetype/dispatcher.ams/src/conf.d/variables/ams_default.vars
Rename `src/main/archetype/dispatcher.ams/src/conf.d/whitelists` template folder to `src/main/archetype/dispatcher.ams/src/conf.d/allowlists`.
Use equitable terminology
**Before (mvn archetype version 24)**
```bash
$ mvn -B archetype:generate \
-D archetypeVersion=24 \
-D appTitle="My Site" \
-D appId="mysite-24" \
-D groupId="com.mysite" \
-D aemVersion=on-premise
$ ls -l mysite-24/dispatcher/src/conf.d/whitelists/
-rw-r--r--  1 glauser  wheel  715 Jan 21 15:43 000_base_whitelist.rules
```
Next, build a mvn archetype 25-SNAPSHOT version from this PR:
```bash
$ cd aem-project-archetype [issue/Equitable_Terminology_Change|✔]
$ mvn -B install -Darchetype.test.skip
$ mvn -B integration-tests
[INFO] [INFO] …
```
=> Use equitable terminology

src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/commerce/experiencefragment/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/xfpage/_cq_dialog/.content.xml
- add proxy component for commerce XF component
=> CIF-1846 - Update AEM archetype after 2021.1.0 CIF release

src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/clientlibs/clientlib-cif/.content.xml
Include category carousel default styles in cif clientlib.
CIF-1906 
Manually.
=> CIF-1906 - Minimal default styling for category carousel

src/main/archetype/pom.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/form/container/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/form/container/new/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/conf/__appId__/settings/wcm/policies/.content.xml
fixes #617 : Update to Core Components 2.15.0
=> Update to Core Components 2.15.0

src/main/archetype/ui.frontend.general/package.json
Solve build issue when running npm start
- removes the deprecated node-sass from package.json
- falls back to the sass package already installed
Tested in an AEM project build on archetype-24
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [  ] New feature (non-breaking change which adds functionality)
=> Fix issue running npm start for front end modules

src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/experiencefragment/_cq_editConfig.xml
sync edit config with Core XF component
fixes #592
=> Experience Fragment edit in new tab is broken

src/main/archetype/core/src/main/java/core/models/HelloWorldModel.java
=> Remove use of deprecated SlingSettingsService in HelloWorldModel.java

src/main/archetype/ui.content/src/main/content/jcr_root/content/experience-fragments/__appId__/.content.xml
- add ca config path for experience fragments
fixes #517
=> [Data Layer] Include Experience Fragments

src/main/archetype/ui.config/src/main/content/jcr_root/apps/__appId__/osgiconfig/config.publish/org.apache.sling.jcr.resource.internal.JcrResourceResolverFactoryImpl.cfg.json
=> Invalid character in config

src/main/archetype/dispatcher.ams/pom.xml, src/main/archetype/dispatcher.cloud/pom.xml, src/main/archetype/it.tests/pom.xml, src/main/archetype/pom.xml, src/main/archetype/ui.frontend.angular/pom.xml, src/main/archetype/ui.frontend.general/pom.xml, src/main/archetype/ui.frontend.react/pom.xml, src/main/archetype/ui.tests/pom.xml
- add maven-assembly-plugin to pluginManagement of parent pom
- set configuration of tarLongFileMode to posix as default fixes #615
=> unify maven-assembly-plugin

src/main/archetype/pom.xml, src/main/archetype/ui.apps/pom.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/msm/__appId___blueprint/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/msm/__appId___blueprint/_jcr_content/.content.xml, src/main/archetype/ui.content/pom.xml, src/main/archetype/ui.content/src/main/content/jcr_root/content/dam/.content.xml
- update aem-nodetypes
- enable node-type validation fixes #611
- make required changes to default content
=> update filevault-package-maven-plugin to 1.1.6

src/main/archetype/ui.config/pom.xml
fix sourceDirectory property fixes #609
=> OOTB path for resource is incorrect in the ui.config package

src/main/resources/META-INF/archetype-post-generate.groovy
=> CQ-4315545 Enabling aem maven analyzer plugin for forms project

src/main/archetype/pom.xml
=> Update aemanalyser-maven-plugin to latest version

src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/clientlibs/clientlib-cif/.content.xml
Include featured category list default styles in CIF client library.
CIF-1921
Manually.
=> CIF-1921 - Minimal default styling for featured category list

.github/workflows/maven-deploy-cm.yml
* Created Github Action that is able to deploy a project created with the latest archetype snapshot to a AEMaaCS environment.
=> Automate testing of archetype-generated project on AEMaaCS

src/main/archetype/all/pom.xml, src/main/archetype/ui.apps.structure/pom.xml, src/main/archetype/ui.apps/pom.xml, src/main/archetype/ui.config/pom.xml, src/main/archetype/ui.content/pom.xml
specify correct cloudManagerTarget property for structure and all package
fixes #635
=> ui.apps.structure doesn't have a CloudManager by-pass definied

src/main/archetype/pom.xml
@review @rismehta @vdua
DOD(Yes)
AEM Forms Core components repo has a new version released with some bugfixes
Updating the archetype for same
=> CQ-4318408 Update core-forms-components version

src/main/archetype/ui.apps.structure/pom.xml, src/main/archetype/ui.config/src/main/content/jcr_root/apps/__appId__/osgiconfig/config/org.apache.sling.jcr.repoinit.RepositoryInitializer-__appId__.config, src/main/archetype/ui.config/src/main/content/jcr_root/apps/__appId__/osgiconfig/config/org.apache.sling.jcr.repoinit.RepositoryInitializer~__appId__.cfg.json, src/main/archetype/ui.content/src/main/content/META-INF/vault/filter.xml, src/main/archetype/ui.content/src/main/content/jcr_root/content/dam/__appId__/.content.xml
* Moved /content/dam/<project> folder creation to repoinit
* Updated filters
Fixes #583
=> Remove too inclusive paths from Archetype #583

src/main/archetype/it.tests/src/main/java/it/tests/PublishPageValidationIT.java
Project created from archetype without any modifications need
an override of the warnings in order to deploy. Fix the Vulnerability
warning shown in CM
=> Address Vulnerability issue reported by CM

src/main/archetype/dispatcher.ams/src/conf.dispatcher.d/cache/ams_author_cache.any
=> Cache client libraries on AMS author

src/main/archetype/dispatcher.ams/src/conf.d/available_vhosts/aem_author.vhost
=> Do not enable gzip for author dispatcher by default

src/main/archetype/pom.xml
=> Update Core Components Version to 2.16.0

src/main/archetype/ui.content/src/main/content/jcr_root/content/__appId__/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/content/__appId__/language-masters/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/content/__appId__/us/.content.xml
- replace foundation redirect component with core component page
fixes #690
=> Replace foundation redirect component

.github/workflows/maven-deploy-cm.yml
This will validate deployment of forms content as part of aem archetype project
Enabling forms for aem archetype project. This will include forms content in the sample project.
Config change for validation
To validate forms content deployment
Manually tested by creating sample project using archetype and enabling forms inclusion
=> CQ-4321852 : [Smoke IT ] Auto-Validation of forms content in archetype

src/main/archetype/ui.content/src/main/content/jcr_root/content/dam/formsanddocuments-themes/__appId__/canvas-3-0/_jcr_content/renditions/theme-json/.content.xml
@review: @sakshi-arora1
We have added the support for editing captcha in themes. In accordance with that editing this theme to support captcha
=> CQ-4313745 Enable captcha component in theme editor

src/main/archetype/pom.xml
Added 'name' attribute to the parent pom.xml
added <name> attribute in the parent pom.xml
=> Updated parent pom.xml to add name property.

src/main/archetype/pom.xml
=> Update Core Components to 2.17.0

src/main/archetype/dispatcher.cloud/src/conf.dispatcher.d/filters/default_filters.any
=>  Allow video formats to be downloadable, in the filters

README.md
Update the command example in readme.
=> Update archetype version in readme

src/main/archetype/pom.xml
CIF 2.0.0 has been released recently and we want to make it available in AEM project archetype.
CIF 2.0.0 requires AEM Core WCM Components 2.17.2, this PR updates this too.
#762 
Manually.
=> Updated POM dependencies to CIF 2.0.0 and Core WCM Components 2.17.2.

src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/commerce/product/.content.xml
* updated product component proxy to v2
CIF-2216
Manually.
=> CIF-2216 - Use v2 of product component in AEM archetype

src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/clientlibs/clientlib-cif/.content.xml, src/main/archetype/ui.frontend.general/src/main/webpack/components/_navigation.scss
Using the default styling of navigation component in AEM archetype.
CIF-1926
Manually.
=> CIF-1926 - Minimal default styling for navigation

src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/page/.content.xml
Upgrade to CIF V2 page component to implement specific category support using urlPath. This PR relates to https://github.com/adobe/aem-core-cif-components/pull/620 and should only be merged after CIF 2.0 components have been released.
CIF-2193
=> CIF-2193 - implement specific category support using urlPath

src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/button/.content.xml
Update CIF Button version to use V2, see https://github.com/adobe/aem-core-cif-components/pull/615
CIF-2153
=> CIF-2153 - update CIF Button version to V2

src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/commerce/teaser/.content.xml
update commerce teaser to new V2 version, see https://github.com/adobe/aem-core-cif-components/pull/625
CIF-2155
=> CIF-2155 - update commerce teaser to new V2 version

README.md
Updating the readme in develop, so people won't get confused with an old version.
=> update readme archetype version

src/main/archetype/pom.xml
=> bump aem analyser to 1.1.8

src/main/resources/META-INF/archetype-post-generate.groovy
Remove one of the factory configurations depending on the AEM version
=> Duplicate RepositoryInitializer Configuration #804

src/main/resources/META-INF/archetype-post-generate.groovy
Remove duplicate RepositoryInitializer configuration. This closes #804
=> Duplicate RepositoryInitializer Configuration

src/main/archetype/pom.xml
Update to CIF Core Components to 2.2.0 release
CIF-2261
=> releng - Update to CIF 2.2.0 release

src/main/archetype/pom.xml
Update to latest release
https://github.com/adobe/aemanalyser-maven-plugin/releases/tag/aemanalyser-maven-plugin-1.2.2
=> Update to aemanalyser plugin 1.2.2

VERSIONS.md
Added version 32 and updated AEM 6.5.X as per System Requirements mentioned at https://github.com/adobe/aem-project-archetype
=> Update Historical Versions

README.md
=> [ReadMe] Update Archetype version in command line argument

VERSIONS.md
As per System Requirements mentioned at https://github.com/adobe/aem-project-archetype/tree/master
=> Update Historical Versions (#838)

src/main/archetype/pom.xml
Update CIF dependencies:
* CIF Core Components 2.4.2
* CIF GraphQL client 1.7.6
* CIF add-on API 2021.11.18.00
CIF-2579
=> CIF-2579 - update CIF dependencies

VERSIONS.md, src/main/archetype/core/src/main/java/core/listeners/SimpleResourceListener.java, src/main/archetype/core/src/test/java/core/listeners/SimpleResourceListenerTest.java
Remove the use of ResourceChangeEvents, fixes #841
=> #841 change listener to resource change listener

src/main/archetype/ui.frontend.angular/package.json, src/main/archetype/ui.frontend.react/package.json
* fix vulnerabilities issues for ui.frontend.react module
* fix vulnerabilities issues in ui.frontend.angular module
=> Issue/849 vulnerable third party (#851)

src/main/archetype/pom.xml
=> Update aem analyser plugin to version 1.3.0

src/main/archetype/dispatcher.ams/pom.xml, src/main/archetype/dispatcher.cloud/pom.xml, src/main/archetype/pom.xml, src/main/resources/META-INF/archetype-pre-package.groovy
=> #859 Use requireTextFileChecksum instead of requireFileChecksum to be platform-agnostic for checking line endings

src/main/archetype/ui.frontend.general/package-lock.json, src/main/archetype/ui.frontend.general/package.json
The latest release fixes an issue with circular dependency. Basically, a file can include itself.
Subsequently, running `npm run prod` fails.
https://github.com/webpack-contrib/mini-css-extract-plugin/issues/733
https://github.com/webpack/webpack/issues/15060
The archetype project for frontend (general) was outdated and running `npm audit` flagged third party package vulnerabilities. This was at the time, I wanted to upgrade package.json, faced issues and opened the above issues. 
Also, I saw that a PR got merged https://github.com/adobe/aem-project-archetype/issues/849.
However, as mentioned in the description, the production build still fails. Last but not least, the `package-lock.json` is not part of the repository and it probably should?
If one pulls the archetype frontend project, it …
=> [Frontend] upgrade glob-import-loader to 1.2.0

src/main/archetype/ui.content/src/main/content/jcr_root/conf/__appId__/settings/wcm/template-types/page/policies/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/conf/__appId__/settings/wcm/template-types/page/structure/.content.xml
* Removes some references to Venia and replace them with the appId variable
Create sample project using:
```bash
mvn -B org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate \
-D archetypeVersion=36-SNAPSHOT\
-D appTitle="My Site" \
-D appId="mysite" \
-D groupId="com.mysite" \
-D aemVersion="cloud" \
-D includeCommerce="y" \
-D commerceEndpoint="https://magento.cloud/graphql"
```
=> CIF-2628 - Remove references to Venia

src/main/archetype/pom.xml
* Update CIF Core Components to version 2.5.0
* Update CIF Add-on API to 2022.01.20.00
=> releng - Update CIF to January release

src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/clientlibs/clientlib-cif/.content.xml, src/main/archetype/ui.frontend.general/src/main/webpack/components/commerce/_navigation.scss
* Removed clientlib from the CIF Core Navigation v2 component
* Added those styles to the `ui.frontend` module to be included by `clientlib-site`.
* Manually
=> CIF-2638 - Move navigation styling to Archetype

src/main/archetype/it.tests/pom.xml
Fixes:
* SLING-11131 - Remove Guava Dependency for CVE-2018-10237 and CVE-2020-8908
* SLING-11124 - Update Apache HTTP Client Dependency for CVE-2020-13956
* Allow to set "forceBasicAuth" for author and publish instance separately
* Address CVEs in transitive dependencies.
* Include new change from aem-testing-clients
* Executed all changed modules against an AEM as a Cloud Service vanilla environment.
=> Bump aem-testing-clients to 1.0.5

README.md, VERSIONS.md
=> @releng : updated README and VERSIONS for 36 release

src/main/archetype/pom.xml
=> Update the AEMAnalyser update to 1.4.6

src/main/archetype/pom.xml
Update the CIF Core Components and CIF Graphql Client to the latest release version.
=> CIF-2734: update CIF Core Components and CIF GQL Client

src/main/archetype/pom.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/image/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/search/.content.xml
- update dependency of core components to 2.19.0
- set proxy search component to v2
fixes #921
=> Update Core Components to v2.19.0

src/main/archetype/pom.xml
Updating to the latest release to get some improvements and bugfixes.
=> Update aemanalyser-maven-plugin to 1.4.8

src/main/archetype/pom.xml
We should update to the latest release: https://github.com/adobe/aemanalyser-maven-plugin/releases/tag/aemanalyser-maven-plugin-1.4.10
=> Update aemanalyser plugin to 1.4.10

src/main/archetype/pom.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/commerce/catalogpage/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/page/.content.xml
Updates the CIF Core Components to the next release (2.9.0) and updates the app page and catalogpage to the CIF Core Components page v3, which inherits from the WCM Core Components Page v3. 
CIF-2289
=> CIF-2289: update cif page to v3

src/main/archetype/pom.xml, src/main/archetype/ui.frontend.react.forms.af/package.json
Upgraded forms core components version to 1.0.14
CQ-4343453
=> CQ-4343453 Upgrade forms core components

src/main/archetype/ui.content/src/main/content/jcr_root/content/dam/__appId__/af_model_sample.json/_jcr_content/renditions/original
=> CQ-4343453 Update sample form for multiple submit fix

src/main/archetype/ui.frontend.react.forms.af/src/Form.tsx
Remove debugger from form.tsx
CQ-4343453
=> CQ-4343453 remove debugger from form.tsx

src/main/archetype/pom.xml
Update the CIF Core Components to the latest release version.
=> CIF-2902: update CIF Core Components to 2.10.0

src/main/archetype/all/pom.xml, src/main/archetype/ui.content/src/main/content/jcr_root/conf/__appId__/settings/wcm/template-types/af-page-v2/structure/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/conf/__appId__/settings/wcm/templates/blank-af-v2/structure/.content.xml, src/main/archetype/ui.frontend.react.forms.af/src/Form.tsx
=> Cq 4346045
