src/main/archetype/ui.apps/src/main/content/jcr_root/apps/sling/servlet/errorhandler/ResponseStatus.java
If you visit non-HTML 404 pages, the mime type is not correctly set and thus, displays the HTML as plain text. For example...
/content/test.jpg
/content/something.json
/content/something-else
All returns 404.html as plain-text.
This pull request sets the content-type to be HTML to display when a file cannot be found. It's probably worth a discussion whether there should be excluded mime-types for this... for example, maybe json should return { response : 'not found' }.
=> Set the content type for non-HTML 404s.

README.md
Proposed changes:
1. Text now reflects archetype v13 (AEM 6.3)
2. Side note at the bottom: The profile "autoInstallPackage" requires the activation of profile "adobe-public". Not sure if this should be added as an activeProfile in settings.xml, though.
=> Updated text for archetype v13 and added side note

src/main/archetype/pom.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/clientlib-base/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/content/breadcrumb/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/content/breadcrumb/clientlib/less/breadcrumb.less, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/content/image/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/content/languagenavigation/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/content/list/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/content/navigation/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/content/search/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/content/text/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/content/title/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/form/button/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/form/container/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/form/container/new/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/form/hidden/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/form/options/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/components/structure/page/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/conf/__confFolderName__/settings/wcm/templates/content-page/structure/.content.xml
- Updates core.wcm.components.all dependency to release 2.0.4
- Adds new proxy components for navigation, language navigation and search components
- Updates existing proxy component versions
- Updates clientlib versions
- Adds the navigation, language navigation and search components to the content page template structure
- Fixes bespoke breadcrumb styles for V2 breadcrumb component
=> Update project archetype to release 2.0.4 of the Core Components

README.md
Updates AEM 6.3 requirement information for V13 - so that we can create a proper release of Archetype V13 without waiting for AEM 6.3 SP2.
=> @releng updates AEM 6.3 requirement info for Archetype Version 13

src/main/archetype/it.launcher/pom.xml
the it.tests generated from the archetype do not run with AEM 6.4 due to mismatch in package dependencies. This PR includes a fix and an optimization to not deploy HTTP clients which is no longer required because recent AEM versions include up-to-date ones.
=> it.tests do not run with AEM 6.4

src/main/archetype/core/pom.xml, src/main/archetype/pom.xml, src/main/archetype/ui.apps/pom.xml
Update to the pom:
* update maven-bundle-plugin to 4.1.0 (generate metadata for OSGI r6 annotations)
* run the maven-bundle-plugin twice to generate metadata also for unittests (so you can use the sling-mocks properly)
* updated sling-mock dependencies
* updated some other dependencies to keep up with AEM 6.3 (sling models, servlet API, ...)
=> Update dependencies & build

src/main/archetype/pom.xml
This bring in multiple fixes, notably [JCRVLT-272](https://issues.apache.org/jira/browse/JCRVLT-272) which caused `mvn test` to fail in multi-module builds.
This fixes  #161
Plugin version update to latest stable release.
=> Update filevault-package-maven-plugin to version 1.0.3

src/main/archetype/core/pom.xml, src/main/archetype/core/src/main/java/core/models/HelloWorldModel.java, src/main/archetype/core/src/test/java/core/filters/LoggingFilterTest.java, src/main/archetype/core/src/test/java/core/models/HelloWorldModelTest.java, src/main/archetype/core/src/test/java/core/servlets/SimpleServletTest.java, src/main/archetype/pom.xml
As this is an archetype for AEM projects and not only for Sling projects it would be very useful for the users to include AEM mocks by default, and not only Sling Mocks.
With only Sling Mocks it's difficult to test code that depends on the AEM API.
Ensured that all includes unit tests still run, and AEM Mocks can be used in the unit tests.
=> Use AEM Mocks instead of Sling Mocks

src/main/archetype/pom.xml
Update from 2.4.4 to 2.4.8
aem-mock 2.4.8 includes some improvements to be more compatible with the latest AEM 6.5.0 uber jar.
=> Update to aem-mock 2.4.8

src/main/archetype/core/pom.xml, src/main/archetype/pom.xml
& update to latest version 2.4.0 of this plugin
=> maven-sling-plugin was renamed to sling-maven plugin

src/main/archetype/ui.content/src/main/content/jcr_root/conf/__confFolderName__/settings/cloudconfigs/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/conf/__confFolderName__/settings/dam/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/conf/__confFolderName__/settings/dam/cfm/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/conf/__confFolderName__/settings/dam/cfm/models/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/conf/__confFolderName__/settings/wcm/segments/.content.xml
This will enable the below 3 configuration settings during archetype execution for generating mid market blueprint projects
Add ContextHub segments
Add Cloud Services
Add Content Fragment Models
=> enable config browser settings

src/main/archetype/core/pom.xml, src/main/archetype/core/src/main/java/core/filters/LoggingFilter.java, src/main/archetype/core/src/main/java/core/listeners/SimpleResourceListener.java, src/main/archetype/core/src/main/java/core/servlets/SimpleServlet.java, src/main/archetype/it.tests/pom.xml, src/main/archetype/pom.xml
=> Upgrade dependency management to OSGi R7

src/main/archetype/core/pom.xml, src/main/archetype/pom.xml
- remove the specific Import-Package header so the default value is used
- remove unnecessary dependency of the javax.inject and javax.annotation artifacts
fixes #211
=> Switch to default Import-Package header

src/main/archetype/ui.frontend/webpack.common.js
Node modules were not being properly resolved by Webpack because the file extension was 'js' instead of '.js' on line 15 of webpack.commons
https://github.com/adobe/aem-project-archetype/issues/226
Allows importing of entire modules vs. only importing their inner /dist js files
Built webpack with '.js' instead of 'js'
=> Changed 'js' to '.js' in resolve.extensions (ui.frontend -> webpack.commons.js)

src/main/archetype/README.md, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/clientlib-base/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/conf/__confFolderName__/settings/wcm/policies/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/conf/__confFolderName__/settings/wcm/template-types/empty-page/policies/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/conf/__confFolderName__/settings/wcm/templates/content-page/policies/.content.xml
Changes the way `clientlib-site` and `clientlib-dependencies` are included as part of the project archetype. Instead of embedding these client libraries as part of `clientlib-base` these would now be included separately and configured via the **Page Template** > **Page Policy**. 
In addition to addressing #245, this also provides more flexibility for how client libraries are included since they can now be configured on a per-template basis.
By separating `clientlib-site` and `clientlib-dependencies` from being embedded as part of `clientlib-base` it is now possible to minify Core Components CSS/JS, Responsive Grid CSS and any other client libraries that live in AEM while allowing client libraries generated by the ui.frontend module to be minified by the ui.frontend module (instead of by …
=> Update of client library inclusion fixes double minification

src/main/archetype/it.launcher/pom.xml
Specified the use of a JUnit4 provider for Maven Failsafe Plugin integration tests in the `it.launcher` `pom.xml` file as per the [JUnit Provider Selection](https://maven.apache.org/surefire/maven-failsafe-plugin/examples/junit-platform.html) portion of the documentation.
- Fixes adobe#243
Running `mvn clean verify -PintegrationTests` now triggers integration tests in the `it.launcher` modules of the project to allow integration tests to run on an AEM server.
This change was tested by running `mvn clean verify -PintegrationTests` against an AEM 6.5 server and validating that the `it.launcher` module successfully ran its server-side sample test.
=> Specifying Maven Failsafe JUnit4 provider for integration tests

CONTRIBUTING.md, PULL_REQUEST_TEMPLATE.md, README.md, pom.xml
The package.json file is currently pointed to `Adobe-Marketing-Cloud`, the repository now currently lives at `adobe`.
- [✓] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [✓] I have read the **CONTRIBUTING** document.
=> fix(package): The repository has moved URL

README.md
Couple of typos in Read Me. (maven profile & archetype number)
Documentation correction.
Developers copy pasting the maven profiles may unknowingly end up with an error.
Validated with sample WKND project.
=> Corrected couple of typos

src/main/archetype/README.md, src/main/archetype/ui.frontend/README.md, src/main/archetype/ui.frontend/package.json, src/main/archetype/ui.frontend/src/main/webpack/static/index.html, src/main/archetype/ui.frontend/webpack.dev.js, src/main/resources/META-INF/maven/archetype-metadata.xml
Provides an initial implementation for issue #246 
Included in the ui.frontend module is a [webpack-dev-server](https://github.com/webpack/webpack-dev-server) that provides live reloading for rapid front-end development outside of AEM. The setup leverages the [html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin) to automatically inject CSS and JS compiled from the ui.frontend module into a static HTML template.
**Important files**
* `ui.frontend/webpack.dev.js` - This contains the configuration for the webpack-dev-serve and points to the html template to use. It also contains a proxy configuration to an AEM instance running on `localhost:4502`.
* `ui.frontend/src/main/webpack/static/index.html` - This is the static HTML that the server will run against. This allows a …
=> Static Webpack Dev Server

src/main/archetype/pom.xml, src/main/archetype/repository-structure/pom.xml, src/main/archetype/ui.apps/pom.xml, src/main/archetype/ui.frontend/assembly.xml, src/main/archetype/ui.frontend/pom.xml
- added ui.frontend as a dependency to the ui.apps module
- exclude ui.frontend module in root pom if frontend module is skipped
fixes #267
=> [Frontend] ui.frontend needs to be build before ui.apps

src/main/archetype/core/pom.xml, src/main/archetype/pom.xml
- add javax.annotation as provided dependency and set minimum version in bundle plugin
fixes #229
=> javax.annotation,version -- Cannot be resolved

src/main/archetype/ui.apps/.gitignore
The .gitignore file was ignoring folders that could have source code which should be tracked
https://github.com/adobe/aem-project-archetype/issues/278
Prevents developers from losing code which should be tracked
Built the archetype from master branch of source. Created a new project from the archetype. Made updates and rebuilt the archetype. Created a new project and diff'ed to validate that the only change was the removed .gitignore file
=> Allow all clientlibs to be tracked by git by default

src/main/archetype/ui.apps/.gitignore
Adds back the content of the `.gitignore` file which was removed in https://github.com/adobe/aem-project-archetype/pull/279, but only if a frontend module is used (which means that the content of the ClientLibs is not provided by the user but generated by Webpack).
https://github.com/adobe/aem-project-archetype/issues/278, https://github.com/adobe/aem-project-archetype/pull/279
See discussion in https://github.com/adobe/aem-project-archetype/pull/279.
=> Ignore ClientLibs generated by frontend module

src/main/archetype/core/pom.xml
- add dependency to org.apache.sling.bnd.models
- add plugin configuration for ModelsScannerPlugin
fixes #297
=> Use org.apache.sling.bnd.models.ModelsScannerPlugin in core project

src/main/archetype/all/pom.xml
- bind clean goal to initialize instead install phase
fixes #289
=> 'all' package gets deleted at end of build

src/main/archetype/ui.frontend.general/webpack.prod.js
Webpack Prod config now minifies JS and CSS.
This fixes a bug where no JS or CSS was getting minified when run through the production configuration.
Yes
- [x ] Bug fix (non-breaking change which fixes an issue)
- [] My change requires a change to the documentation.
- [] I have updated the documentation accordingly.
- [] I have added tests to cover my changes.
- [] All new and existing tests passed.
=> Bug Fix: Prod Webpack config now minifies JS and CSS

README.md, src/main/archetype/all/pom.xml, src/main/archetype/core/pom.xml, src/main/archetype/pom.xml, src/main/archetype/ui.apps/pom.xml, src/main/archetype/ui.frontend.angular/package.json
- add core components dependency only for aemVersion != cloud
=> Archetype without Core Comp Dependency for Cloud Projects

src/main/archetype/ui.frontend.general/src/main/webpack/site/main.scss
The component based scss files are not merged by the frontend build as the path reference is wrong.
=> Fix wrong path to component scss files

src/main/archetype/pom.xml, src/main/resources/META-INF/archetype-post-generate.groovy
See #395
See #395
The build will be faster as it does not have to query an additional Maven repository. Also, for corporate environments, fewer firewall exceptions to ask for.
- ran the build
- generated a project using the archetype
- built the generated project
=> Use Maven central for the AEM as a cloud service SDK

README.md, pom.xml
Change the group id to com.adobe.aem to align with public Adobe AEM artifacts.
This changes the group id to com.adobe.aem.
While this can be seen as an incompatible change, it is not affecting existing projects as an archetype is used once in the beginning. Changing the group id alligns with other public artifacts around AEM like the SDK for Cloud Service etc.
=> Change group id to com.adobe.aem

src/main/archetype/ui.content/src/main/content/META-INF/vault/filter.xml, src/main/archetype/ui.content/src/main/content/jcr_root/conf/__appId__/settings/cloudconfigs/commerce/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/var/commerce/products/__appId__-default/.content.xml, src/main/resources/META-INF/archetype-post-generate.groovy
Create the `/var/commerce/products/${appId}-default` folder when the project includes commerce features, but not for the `cloud` type.
CIF-1489
Feature parity with the AEM CIF Project Archetype
Functional testing
=> CIF-1489 - Default product binding is missing in the Venia repo

src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/xfpage/_cq_dialog/.content.xml, src/main/resources/META-INF/archetype-post-generate.groovy
* It is now possible to define the CIF pages in the properties of the `xfpage` component. Only for `includeCommerce=y`.
https://github.com/adobe/aem-cif-guides-venia/pull/30
https://github.com/adobe/aem-core-cif-components/pull/374
=> CIF-1538 - Expose CIF page paths in xfpage property dialog

src/main/archetype/pom.xml
componentGroupName is not defined in generated project. So it currently only shows as :
fixed it to use whatever is set as appTitle in archetype
fixes #386
local building and running archetype 
- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] All new and existing tests passed.
=> componentGroupName is not defined in generated project

src/main/archetype/dispatcher.ams/assembly.xml, src/main/archetype/dispatcher.ams/pom.xml, src/main/archetype/dispatcher.ams/src/conf.d/autoindex.conf, src/main/archetype/dispatcher.ams/src/conf.d/available_vhosts/000_unhealthy_author.vhost, src/main/archetype/dispatcher.ams/src/conf.d/available_vhosts/000_unhealthy_publish.vhost, src/main/archetype/dispatcher.ams/src/conf.d/available_vhosts/__appId___publish.vhost, src/main/archetype/dispatcher.ams/src/conf.d/available_vhosts/aem_author.vhost, src/main/archetype/dispatcher.ams/src/conf.d/available_vhosts/aem_flush.vhost, src/main/archetype/dispatcher.ams/src/conf.d/available_vhosts/aem_health.vhost, src/main/archetype/dispatcher.ams/src/conf.d/available_vhosts/aem_lc.vhost, src/main/archetype/dispatcher.ams/src/conf.d/available_vhosts/aem_publish.vhost, src/main/archetype/dispatcher.ams/src/conf.d/logformat.conf, src/main/archetype/dispatcher.ams/src/conf.d/mimetypes3d.conf, src/main/archetype/dispatcher.ams/src/conf.d/remoteip.conf, src/main/archetype/dispatcher.ams/src/conf.d/security.conf, src/main/archetype/dispatcher.ams/src/conf.d/userdir.conf, src/main/archetype/dispatcher.ams/src/conf.d/welcome.conf, src/main/archetype/dispatcher.ams/src/conf.d/whitelists/000_base_whitelist.rules, src/main/archetype/dispatcher.ams/src/conf.dispatcher.d/filters/ams_author_filters.any, src/main/archetype/dispatcher.ams/src/conf.dispatcher.d/renders/ams_author_renders.any, src/main/archetype/dispatcher.ams/src/conf.dispatcher.d/renders/ams_lc_renders.any, src/main/archetype/dispatcher.ams/src/conf.dispatcher.d/renders/ams_publish_renders.any, src/main/archetype/dispatcher.ams/src/conf.modules.d/01-cgi.conf, src/main/archetype/dispatcher.ams/src/conf/httpd.conf, src/main/archetype/dispatcher.cloud/assembly.xml, src/main/archetype/dispatcher.cloud/pom.xml, src/main/archetype/dispatcher.cloud/src/conf.dispatcher.d/dispatcher.any, src/main/archetype/dispatcher.cloud/src/conf.dispatcher.d/renders/default_renders.any
- made sure all dispatcher config files (xml based and any format) used tabs for indentations as this seems to be the commonly used.
- made sure that pom.xml and assembly.xml in the root of the dispatcher modules uses 4 space indentations and not 2, same as in the other modules.
- fixed some wrong indentations
fixed #443
=> Use consistent indentation in the dispatcher configuration

src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/clientlibs/clientlib-grid/less/grid.less
* Added CSS rule to show hidden components in unhide mode
Fixes #499
=> "Unhide components" on a page does not list hidden components

src/main/archetype/.gitignore
I am integrating AEM projects generated from this archetype with bigger Gradle builds. Dispatcher configuration is being provided to HTTPD via Docker/volume. As a result of o such configuration, I am achieving a live-reloading feature (without a need for building ZIP by Maven) for easy and comfortable work with Dispatcher config files. However, file: 'dispatcher/src/conf.d/variables/default.vars' need to be provided externally to be able to start HTTPD service. As it is not Git-ignored right now, and the whole path 'dispatcher/src/conf.d' is mounted as a volume in my case, after each project generation I need to append a line for ignoring this file manually (and tell everybody else to do that also), because after providing it externally Git recognizes it as a new untracked file. It would …
=> Dispatcher vars file ignored

src/main/archetype/dispatcher.ams/src/conf.dispatcher.d/filters/ams_publish_filters.any, src/main/archetype/dispatcher.cloud/src/conf.dispatcher.d/filters/filters.any
To support the following roadmap [0], we agreed to add filters that will allow the dispatcher to expose files that end with a `webmanifest` extension.
#551
The change relates to [0] and has been suggested to be added to the archetype.
[0] CQ-4293019 - Enhance AEM Sites to make sites installable (incl. offline content) using PWA
Tested on an internal Cloud Service instance.
Probably unnecessary
=> Add filter to allow dispatcher to expose files with a webmanifest extension

src/main/archetype/README.md, src/main/archetype/analyse/pom.xml, src/main/archetype/pom.xml, src/main/resources/META-INF/archetype-post-generate.groovy, src/main/resources/META-INF/maven/archetype-metadata.xml
AEMaaCS provides extended analysis of projects in the build and deployment pipeline. This includes running the Feature Model Analysers on the content packages. If these analysers find a problem they will fail the build and the developer needs to rectify the problem. 
This can be problematic for developers as there is an amount of time between these failures in the deployment pipelines and the actual development of the content packages.
The new [aemanalyser-maven-plugin](https://github.com/adobe/aemanalyser-maven-plugin/blob/main/aemanalyser-maven-plugin/README.md) makes it possible to run these analysers that are already running in the pipeline on the developer's local machine as part of the Maven build. This will give much quicker feedback to the developer and shortens the developer life …
=> Support aemanalyser-maven-plugin in the generated projects (#533)

src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/xfpage/_cq_dialog/.content.xml
- add product references to experience fragments (cloud only)
Manually tested.
See https://github.com/adobe/aem-cif-guides-venia/pull/90 for the result in the Venia demo.
=> CIF-1177 - Product reference tab for Experience Fragments

pom.xml
- add exclude to plugin configuration
fixes #581
=> Exclude node-modules files from maven-checkstyle-plugin

src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/xfpage/_cq_dialog/.content.xml
Add category references tab and picker to XF component (cloud only)
Manual testing
See https://github.com/adobe/aem-cif-guides-venia/pull/97 for results in Venia project
=> CIF-1911: Add category references tab + picker for XF to AEM project archetype

src/main/archetype/ui.frontend.angular/package.json, src/main/archetype/ui.frontend.angular/src/app/app.module.ts, src/main/archetype/ui.frontend.angular/src/app/components/import-components.ts, src/main/archetype/ui.frontend.react/package.json, src/main/archetype/ui.frontend.react/src/components/import-components.js
Adds the basic core components to the React / Angular SPA, such as Carousel, Tabs, Download etc.
https://github.com/adobe/aem-project-archetype/issues/584
This will make partners aware that we have react / angular core components, and therefore don't need to reinvent the wheel.
Unit Tests
=> Add core components to react and angular

src/main/archetype/it.tests/pom.xml, src/main/archetype/it.tests/src/main/java/it/tests/HtmlUnitClient.java, src/main/archetype/it.tests/src/main/java/it/tests/PublishPageValidationIT.java
A simple integration test which is able to validate a page on publish:
* Check external references (Clientlibs, images, renditions of Image Core Components)
* Check the statuscode and the size of the external references (should always be 200 and a non-zero byte size)
It uses the HTMLUnit library and can easily be extended to test other features of the page, too!
Thanks @volteanu for your help and inspiration!
=> add an additional IT test

src/main/archetype/pom.xml
This update includes support for CIF add-ons in the aemanalyser-maven-plugin.
=> Update aemanalyser-maven-plugin to version 0.9.0

README.md, src/main/archetype/core/pom.xml, src/main/archetype/pom.xml, src/main/archetype/ui.apps/pom.xml, src/main/archetype/ui.content/pom.xml
- remove classifier from uber-jar dependency
- update minimum 6.4 and 6.5 AEM version in system requirements
fixes #607
=> remove classifier for uber-jar

src/main/archetype/ui.frontend.general/package.json, src/main/archetype/ui.frontend.general/webpack.common.js
I've replaced the `webpack-import-glob-loader` dev dependency with `glob-import-loader`.
#630 
The dependency [`webpack-import-glob-loader`](https://github.com/adobe/aem-project-archetype/blob/master/src/main/archetype/ui.frontend.general/package.json#L52) has been left untouched for 2 years after being forked [from a project](https://github.com/terpiljenya/import-glob) which was been untouched for 4 years. It still works fine for most cases but I've run across a couple of issues:
1. It does not support the new Sass at-rules [@use](https://sass-lang.com/documentation/at-rules/use) and [@forward](https://sass-lang.com/documentation/at-rules/forward). Granted, the plugin is called webpack-_import_-glob-loader, however, the [@import directive has been …
=> Replace `webpack-import-glob-loader` with `glob-import-loader`.

.github/workflows/maven-deploy-cm.yml, README.md, VERSIONS.md, pom.xml, src/main/archetype/.gitattributes, src/main/archetype/pom.xml
Adding .gitattributes file to archetype assets to avoid invalid line endings on immutable dispatcher files
Adding the .gitattributes file will unify line ending handling for committers using different operating systems so that the immutable Dispatcher files do not get corrupted during commits.
Fixes #661 
In certain development environments that may be configured with different GIT line ending configurations, it is possible for developers to unwillingly commit files with invalid line endings which will break the Dispatcher module's immutable file check due to invalid MD5 hashes.
Followed the steps to reproduce documented in #661 but the project build was now successful
N/A
=> Adding .gitattributes file to archetype assets

src/main/archetype/dispatcher.ams/src/conf.d/available_vhosts/000_unhealthy_author.vhost, src/main/archetype/dispatcher.ams/src/conf.d/available_vhosts/000_unhealthy_publish.vhost, src/main/archetype/dispatcher.ams/src/conf.d/available_vhosts/__appId___publish.vhost, src/main/archetype/dispatcher.ams/src/conf.d/available_vhosts/aem_author.vhost, src/main/archetype/dispatcher.ams/src/conf.d/available_vhosts/aem_lc.vhost, src/main/archetype/dispatcher.ams/src/conf.d/available_vhosts/aem_publish.vhost
Remove User-Agent from vary header to improve caching on CDN/proxy
=> Remove setting that adds User-Agent to vary header

src/main/resources/META-INF/maven/archetype-metadata.xml
Include opt-in marker file for direct source mode for cloud dispatcher config
#703
Cloud dispatcher config introduces direct source mode to apply dispatcher configs from _conf.d_ and _conf.dispatcher.d_ directly instead of the  limited one generated by dispatcher validator. To use this mode an opt-in file needs to exist in dispatcher config folder. Since this mode allows for more flexibility in cloud dispatcher config it should be enabled by default.
Generating new project from changed archetype:
```
mvn -B archetype:generate \
-D archetypeVersion=28-SNAPSHOT \
-D appTitle="Use dispatcher sources directly mode" \
-D appId="dispatcher-config-direct-sources" \
-D groupId="com.adobe.aem" \
-D aemVersion=cloud …
```
=> Include opt-in marker file for direct source mode for cloud dispatcher config

src/main/archetype/dispatcher.cloud/src/conf.dispatcher.d/filters/default_filters.any
sync immutable file _default_filters.any_ with dispatcher SDK 2.0.57
Syncing immutable file _default_filters.any_ from dispatcher SDK 2.0.57.
#715
(follow up from #668 / #669)
Immutable files should not be different between SDK and archetype.
Generating new project from changed archetype:
```
mvn -B archetype:generate \
-D archetypeVersion=28-SNAPSHOT \
-D appTitle="Dispatcher config immutability check 2" \
-D appId="dispatcher-config-immutability2" \
-D groupId="com.adobe.aem" \
-D aemVersion=cloud
```
Run `bin/validate.sh archetype/dispatcher-config-immutability2/dispatcher/src` against generated project successfully (including immutable config files check this time).
n/a
=> sync immutable file default_filters.any with dispatcher SDK 2.0.57

src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/commerce/experiencefragment/.content.xml
Changed title of commerce experience fragment component to "Commerce Experience Fragment".
CIF-2135
Manually.
=> CIF-2135 - Rename component to "Commerce Experience Fragment"

src/main/archetype/ui.frontend.general/README.md, src/main/archetype/ui.frontend.general/package.json, src/main/archetype/ui.frontend.general/webpack.dev.js
Currently, the `watch` script in the ui.frontend.general module does not work in Windows. Running parallel scripts with `&` only works on unix based systems.
This PR simplifies the script to utilize the `webpack-shell-plugin` and it's `onBuildExit` hook to ship the clientlib bundle to a local AEM instance when the webpack process completes instead of having to run multiple watchers in parallel.
#683 #684 
* Make the `watch` script cross-platform.
* Tested locally on Windows and Mac after making the updates and generating a new project with the updated archetype.
=> chore: fix frontend general watch script

src/main/archetype/dispatcher.cloud/src/conf.dispatcher.d/clientheaders/default_clientheaders.any, src/main/archetype/dispatcher.cloud/src/conf.dispatcher.d/filters/default_filters.any
sync dispatcher immutable files with dispatcher SDK 2.0.60
Syncing dispatcher immutable files from dispatcher SDK 2.0.60.
#739
Immutable files should not be different between SDK and archetype.
Generating new project from changed archetype:
```
mvn -B archetype:generate \
-D archetypeVersion=28-SNAPSHOT \
-D appTitle="Dispatcher config immutability check SDK 2.0.60" \
-D appId="dispatcher-config-immutability-sdk-2-0-60" \
-D groupId="com.adobe.aem" \
-D aemVersion=cloud
```
Run `bin/validate.sh archetype/dispatcher-config-immutability-sdk-2-0-60/dispatcher/src` against generated project successfully (including immutable config files check this time).
n/a
=> sync dispatcher immutable files with dispatcher SDK 2.0.60

src/main/archetype/ui.frontend.general/README.md, src/main/archetype/ui.frontend.general/package.json, src/main/archetype/ui.frontend.general/webpack.dev.js
Reverts adobe/aem-project-archetype#688
- This doesn't seem to work on MacOs / linux.
Will need to be tested cross-platform
=> Revert "chore: fix frontend general watch script"

pom.xml, src/main/archetype/pom.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/xfpage/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/xfpage/body.html, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/xfpage/customfooterlibs.html, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/xfpage/customheaderlibs.html, src/main/archetype/ui.content/src/main/content/jcr_root/conf/__appId__/settings/wcm/templates/spa-page-template/structure/.content.xml, src/main/archetype/ui.content/src/main/content/jcr_root/conf/__appId__/settings/wcm/templates/xf-web-variation/policies/.content.xml, src/main/archetype/ui.frontend.angular/src/app/components/import-components.ts, src/main/resources/META-INF/archetype-post-generate.groovy
Integrate the latest changes in the spa core, to provide experience fragments OOTB, also in the SPA editor.
https://github.com/adobe/aem-project-archetype/issues/744
Partners are struggeling with the SPA editor + Experience Fragments. It's possible but requires some hacking.
This bootstraps now along with the new SPA core updates provides a clean solution OOTB.
Tested this locally against live AEM instances on:
Angular
React
General (making sure the normal project doesn't break)
=>  integrating experience fragments support for the spa editor

src/main/archetype/pom.xml
See #752  - this profile is not necessary for cloud service anymore, therefore it should be removed
Make the profile optional
See #752
=> Don't include adobe-public profile for cloud service

src/main/archetype/pom.xml
This fixes a johnzon-core JSON parsing issue:
https://github.com/adobe/aemanalyser-maven-plugin/issues/91
=> Update to aemanalyser-maven-plugin 1.1.2

src/main/archetype/it.tests/src/main/java/it/tests/PublishPageValidationIT.java
* Disable the PublishPageValidationIT test for the moment
* In case a resource return a statuscode 200, but a 0-byte response body, just warn (instead of failing)
* #794
=> #794 ignore PublishPageValidationIT for the moment

src/main/archetype/core/pom.xml, src/main/archetype/core/src/test/java/core/models/HelloWorldModelTest.java, src/main/archetype/core/src/test/java/core/testcontext/AppAemContext.java, src/main/archetype/pom.xml
Fixes #798 
This PR depends on #796 because the plugin for AEM mocks was first released in Core Components 2.17.10
* Introduce Core Components Plugin for AEM Mocks
* this requires to always set a property core.wcm.components.version and include the core.wcm.components.core dependency - for cloud projects it's only required in "test" scope to have the model implementation classes available in the test classpath
* update to AEM Mocks 4.1.2 for both cloud and non-cloud projects
* remove obsolete dependencies exclusions for AEM Mocks
* introduce a test context class `AppAemContext` as example to prepare test setup logic required for every unit test in the project
=> #798 Introduce Core Components Plugin for AEM Mocks & Update AEM Mocks

src/main/archetype/ui.tests/Dockerfile
* Changed to specified Node version
Closes #828
=> ui.tests module should use a specified version of Node JS in the Docker container

src/main/archetype/ui.tests/test-module/lib/util/forms.selectors.js, src/main/archetype/ui.tests/test-module/specs/aem/forms.js
Fixed FDM data source tests failing in firefox browser
wdio getValue function on a coral-select element is returning null in firefox browser and element value in chrome browser.
causing test to fail in firefox browser. changing tests to get value from input element inside coral-select.
verified tests in chrome, firefox browser (with and without headless) in docker and local execution.
=> CQ-4312433 fixed data source test failing in firefox

src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/accordion/new/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/carousel/new/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/container/new/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/tabs/new/.content.xml
- switched superType of wcm/foundation/components/parsys/newpar to core/wcm/components/container/v1/container/new
fixes #772
=> Remove reference to legacy foundation components

src/main/archetype/it.tests/pom.xml
Upgrade aem-cloud-testing-clients to v1.0.0, which includes the fixes for CVE-2021-20190 and CVE-2016-6798.
=> Upgrade aem-cloud-testing-clients to v1.0.0

src/main/archetype/core/pom.xml, src/main/archetype/core/src/test/java/core/testcontext/AppAemContext.java, src/main/archetype/pom.xml
Fixes #847 
* Update to latest AEM Mocks version (which includes some important updates from sling-mocks osgi-mock)
* include Sling Context-Aware Configuration plugin to test code which uses context-aware configuration
* refactor AppAemContext a bit to make it easier to test with different resource resolver types
* also update JUnit and Mockito testing dependencies
=> #847 Update AEM Mocks and other testing dependencies

src/main/resources/META-INF/maven/archetype-metadata.xml
Adding .gitattributes to archetype-metadata.xml. File previously added in #661 but missing from new projects when using the `mvn -B archetype:generate` command.
* Relates to #661 
* Fixes #825 
In certain development environments that may be configured with different GIT line ending configurations, it is possible for developers to unwillingly commit files with invalid line endings which will break the Dispatcher module's immutable file check due to invalid MD5 hashes.
Yes. Steps included:
* Adding changes locally
* Building archetype project with `mvn clean install -Pit-basic`
* Run `mvn -B archetype:generate ... -DarchetypeVersion=31-SNAPSHOT`
* Confirm presence of `.gitattributes` in new project
=> Adding .gitattributes to archetype-metadata.xml. Fixes #825.

pom.xml, src/main/resources/META-INF/archetype-post-generate.groovy
maven-archetype-plugin 3.2.1 which contains "groovy-all" dependency by default
Fixes #857
=> #857 make compatible with maven-archetype-plugin 3.2.1

src/main/archetype/dispatcher.cloud/src/conf.d/dispatcher_vhost.conf
Disable access to default CGI scripts delivered with Alpine's `apache2` package.
Alpine Linux [apache2](https://pkgs.alpinelinux.org/package/edge/main/x86_64/apache2) package contains [a few sample files](https://pkgs.alpinelinux.org/contents?file=&path=%2Fvar%2F*&name=apache2&branch=edge&repo=main&arch=x86_64) that get installed in `/var/www` directory. 
[httpd.conf](https://pkgs.alpinelinux.org/contents?file=httpd.conf&path=&name=apache2&branch=edge&repo=main&arch=x86_64) opens up access to `/var/www/localhost/cgi-bin/` directory:
```
<IfModule alias_module>
ScriptAlias /cgi-bin/ "/var/www/localhost/cgi-bin/"
</IfModule>
<Directory "/var/www/localhost/cgi-bin">
AllowOverride None
Options None
Require all granted
</Directory>
```
That means you can go to `/cgi-bin/printenv` (or other …
=> Disable access to default CGI scripts

src/main/archetype/ui.config/src/main/content/jcr_root/apps/__appId__/osgiconfig/config/org.apache.sling.jcr.repoinit.RepositoryInitializer~__appId__.cfg.json
Generated repoinit script (`ui.config/src/main/content/jcr_root/apps/minimal/osgiconfig/config/org.apache.sling.jcr.repoinit.RepositoryInitializer~minimal.cfg.json`) on 6.5 and cloud looks like this:
```json
{
"scripts": [
"create path (sling:OrderedFolder) /content/dam/minimal",
"create path (nt:unstructured) /content/dam/minimal/jcr:content",
"set properties on /content/dam/minimal/jcr:content",
"set cq:conf{String} to /conf/minimal",
"set jcr:title{String} to \"Minimal\"",
"end"
]
}
```
This PR merges the last four lines into a single script
```json
{
"scripts": [
"create path (sling:OrderedFolder) /content/dam/minimal",
"create path (nt:unstructured) /content/dam/minimal/jcr:content",
"set properties on /content/dam/minimal/jcr:content\n  set cq:conf{String} to /conf/minimal\n  set …
```
=> Correct generated repoinit script

src/main/resources/META-INF/archetype-post-generate.groovy
Removes unused Forms assets from `ui.tests` module if **not** a Forms project
Issue #874 
When generating a vanilla AEM project there is no need to include 300+ images that are only for AEM Forms projects. FWIW including 300+ images for a Forms project seems excessive...but thats neither here nor there
Ran using `it-tests` profile and generated a non-forms project using the following command:
```
mvn -B org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate \
-D archetypeVersion=36-SNAPSHOT\
-D appTitle="My Site" \
-D appId="mysite" \
-D groupId="com.mysite"
```
=> add rule to remove forms ui test assets if not a forms project

src/main/archetype/pom.xml
=> Update aemanalyser maven plugin to 1.4.0

src/main/archetype/dispatcher.cloud/src/conf.d/dispatcher_vhost.conf, src/main/archetype/dispatcher.cloud/src/conf.dispatcher.d/filters/default_filters.any
…
Disable POST requests for Graphql persisted queries
Immutable files should not be different between SDK and archetype.
=> SITES-5185 - Ensure all GraphQL Queries to publisher are using Persistent Queries and not POST requests

src/main/archetype/all/pom.xml, src/main/archetype/core/pom.xml, src/main/archetype/ui.apps/pom.xml, src/main/archetype/ui.content/src/main/content/jcr_root/conf/__appId__/settings/wcm/templates/blank-af-v2/.content.xml, src/main/archetype/ui.frontend.react.forms.af/src/Form.tsx, src/main/archetype/ui.frontend.react.forms.af/src/index.tsx, src/main/archetype/ui.frontend.react.forms.af/webpack.common.js
=> CQ-4343453 Exclude forms core components if cloud

src/main/archetype/dispatcher.cloud/src/conf.d/available_vhosts/default.vhost, src/main/archetype/dispatcher.cloud/src/conf.d/dispatcher_vhost.conf, src/main/archetype/dispatcher.cloud/src/conf.d/rewrites/default_rewrite.rules, src/main/archetype/dispatcher.cloud/src/conf.dispatcher.d/cache/default_rules.any
GraphQL persisted queries should be cached by default at dispatcher level. 
The query parameters sent in the request via dispatcher need to be encoded. One example of such query is
https://publish-p33706-e135212.adobeaemcloud.com/graphql/execute.json/aem-cplotusonlinecommerce-project/getMarketingBannersList%3Btag%3Dmarketing-banner-homepage%3Bpath%3D%2Fcontent%2Fdam%2Faem-cplotusonlinecommerce-project%2Fth%2Fen%2Fhome
=> SITES-3659 - [Odin] Review Dispatcher config for Odin and contribute generic parts - Persisted queries

.github/workflows/maven-deploy-cm.yml, src/main/archetype/all/pom.xml, src/main/archetype/pom.xml
* Only include examples content as the Forms Core Components are already provided.
Fixes #956
=> AEMaaCS image build fails due to Core Forms Components artifacts

src/main/archetype/ui.content/src/main/content/jcr_root/conf/__appId__/settings/wcm/templates/landing-page/initial/.content.xml
* Updated `landing-page` template to set and enable the `navRoot` property by default.
* https://github.com/adobe/aem-cif-guides-venia/pull/303
=> CIF-2673 - Add navRoot default to landing page template

src/main/archetype/ui.tests/test-module/package.json
Update package.json to add moment npm dependency that fails on Mac OS.
This issue was reported on https://github.com/adobe/aem-project-archetype/issues/891
npm was complaining on a dependency: [INFO] Error: Cannot find module 'moment' 
Added the latest moment npm dependency under the /ui.tests/test-module/package.json
"moment": "^2.29.1"
https://github.com/adobe/aem-project-archetype/issues/891
build failed when executing the tests when running the command:  mvn verify -Pui-tests-local-execution 
Tested this locally on two Macs
=> Update package.json to add moment npm dependency that fails on Mac OS

src/main/archetype/ui.frontend.react.forms.af/package.json
@review @vdua
DOD(Yes)
The archetype projects makes use of front end maven plugin to build the forms front end module. This plugin does not expose npx in the current execution context. Hence, the build fails if npx is not present globally in the execution context.
=> CQ-4347346 Removing npx dependency from package.json

src/main/archetype/dispatcher.cloud/src/conf.d/dispatcher_vhost.conf, src/main/archetype/dispatcher.cloud/src/conf.d/enabled_vhosts/vhosts.conf, src/main/archetype/dispatcher.cloud/src/conf.dispatcher.d/available_farms/default.farm, src/main/archetype/dispatcher.cloud/src/conf.dispatcher.d/cache/marketing_query_parameters.any, src/main/archetype/dispatcher.cloud/src/conf.dispatcher.d/clientheaders/default_clientheaders.any, src/main/archetype/dispatcher.cloud/src/conf.dispatcher.d/enabled_farms/farms.any
This PR updates the dispatcher default files to the latest version of dispatcher 2.0.120. 
It also includes the new marketing parameters that are active by default in this archetype to encourage these as defaults for new projects.
=> Update dispatcher configuration to dispatcher version 2.0.120

README.md
CQDOC-18946
Added note to README.md about valid Java package name for groupID
See above
CQDOC-18946
It was a good suggestion from a reader. https://github.com/AdobeDocs/experience-manager-core-components.en/issues/31
Same change passed MD validation in our public docs. See PR#214 on the Core Components repo.
None
=> Add note about valid Java package name for groupID

src/main/archetype/pom.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/commerce/list/.content.xml, src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appId__/components/list/.content.xml
Added proxy component for commerce list.
CIF-2842
Manually.
=> CIF-2842 - Extend List component to list pages by product or category

src/main/archetype/ui.frontend.react.forms.af/src/Form.tsx
=> [CQ-4347128] add thankyoumessage & thankyoupage post submit for headless

src/main/archetype/ui.content/src/main/content/jcr_root/conf/__appId__/settings/wcm/policies/.content.xml
Enable Web Optimized Images by default on Image component via the generated policy, using the policy property 
`enableAssetDelivery=true`
This setting should only be set for AEM as a Cloud Service projects
N/A
Promotes the use of the high-valuable Web Optimized Images for images in AEM as a Cloud Service.
Using Github projects automated tests w/ this PR.
- [] My change requires a change to the documentation.
=> Enable Web Optimized Images by default on Image component
